/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qltrungtamtt;

/**
 *
 * @author PHAN CANH TOAN
 */
public class QuanLyForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public QuanLyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnTaiKhoan11 = new javax.swing.JButton();
        btnTaiKhoan12 = new javax.swing.JButton();
        btnTaiKhoan13 = new javax.swing.JButton();
        btnTaiKhoan14 = new javax.swing.JButton();
        btnTaiKhoan15 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnTaiKhoan = new javax.swing.JButton();
        btnQuanLy = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vtbChungChi = new javax.swing.JButton();
        btnGiangVien = new javax.swing.JButton();
        btnNLGiangDay = new javax.swing.JButton();
        btnDT_HP = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        btnPhanCong = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnPhieuThu = new javax.swing.JButton();
        btnXepLop = new javax.swing.JButton();
        btnTKB = new javax.swing.JButton();
        btnDiemDanh = new javax.swing.JButton();
        btnToChucThi = new javax.swing.JButton();
        btnQTDangki = new javax.swing.JButton();
        btnDangKiThi = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnTaiKhoan11.setBackground(new java.awt.Color(0, 0, 0));
        btnTaiKhoan11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaiKhoan11.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan11.setText("Tài Khoản");

        btnTaiKhoan12.setBackground(new java.awt.Color(0, 0, 0));
        btnTaiKhoan12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaiKhoan12.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan12.setText("Tài Khoản");

        btnTaiKhoan13.setBackground(new java.awt.Color(0, 0, 0));
        btnTaiKhoan13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaiKhoan13.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan13.setText("Tài Khoản");

        btnTaiKhoan14.setBackground(new java.awt.Color(0, 0, 0));
        btnTaiKhoan14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaiKhoan14.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan14.setText("Tài Khoản");

        btnTaiKhoan15.setBackground(new java.awt.Color(0, 0, 0));
        btnTaiKhoan15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaiKhoan15.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan15.setText("Tài Khoản");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        btnTaiKhoan.setBackground(new java.awt.Color(0, 0, 0));
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan.setText("Tài Khoản");
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnQuanLy.setBackground(new java.awt.Color(255, 0, 0));
        btnQuanLy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLy.setText("Quản Lý");

        btnHelp.setBackground(new java.awt.Color(0, 0, 0));
        btnHelp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.setText("Trợ Giúp");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/profile-user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vtbChungChi.setBackground(new java.awt.Color(0, 0, 0));
        vtbChungChi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vtbChungChi.setForeground(new java.awt.Color(255, 255, 255));
        vtbChungChi.setText("Chứng chỉ");
        vtbChungChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtbChungChiActionPerformed(evt);
            }
        });

        btnGiangVien.setBackground(new java.awt.Color(0, 0, 0));
        btnGiangVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGiangVien.setForeground(new java.awt.Color(255, 255, 255));
        btnGiangVien.setText("Giảng viên");
        btnGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiangVienActionPerformed(evt);
            }
        });

        btnNLGiangDay.setBackground(new java.awt.Color(0, 0, 0));
        btnNLGiangDay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNLGiangDay.setForeground(new java.awt.Color(255, 255, 255));
        btnNLGiangDay.setText("NL Giảng dạy");
        btnNLGiangDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNLGiangDayActionPerformed(evt);
            }
        });

        btnDT_HP.setBackground(new java.awt.Color(0, 0, 0));
        btnDT_HP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDT_HP.setForeground(new java.awt.Color(255, 255, 255));
        btnDT_HP.setText("Khóa ĐT, Học Phí");
        btnDT_HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDT_HPActionPerformed(evt);
            }
        });

        btnHocVien.setBackground(new java.awt.Color(0, 0, 0));
        btnHocVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHocVien.setForeground(new java.awt.Color(255, 255, 255));
        btnHocVien.setText("Học viên");
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });

        btnPhanCong.setBackground(new java.awt.Color(0, 0, 0));
        btnPhanCong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPhanCong.setForeground(new java.awt.Color(255, 255, 255));
        btnPhanCong.setText("Phân công");
        btnPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanCongActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(0, 0, 0));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnPhieuThu.setBackground(new java.awt.Color(0, 0, 0));
        btnPhieuThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPhieuThu.setForeground(new java.awt.Color(255, 255, 255));
        btnPhieuThu.setText("Phiếu thu");
        btnPhieuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuThuActionPerformed(evt);
            }
        });

        btnXepLop.setBackground(new java.awt.Color(0, 0, 0));
        btnXepLop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXepLop.setForeground(new java.awt.Color(255, 255, 255));
        btnXepLop.setText("Xếp lớp");
        btnXepLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXepLopActionPerformed(evt);
            }
        });

        btnTKB.setBackground(new java.awt.Color(0, 0, 0));
        btnTKB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTKB.setForeground(new java.awt.Color(255, 255, 255));
        btnTKB.setText("Thời khóa biểu");
        btnTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKBActionPerformed(evt);
            }
        });

        btnDiemDanh.setBackground(new java.awt.Color(0, 0, 0));
        btnDiemDanh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDiemDanh.setForeground(new java.awt.Color(255, 255, 255));
        btnDiemDanh.setText("Điểm danh GV");
        btnDiemDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemDanhActionPerformed(evt);
            }
        });

        btnToChucThi.setBackground(new java.awt.Color(0, 0, 0));
        btnToChucThi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnToChucThi.setForeground(new java.awt.Color(255, 255, 255));
        btnToChucThi.setText("Tổ chức thi");
        btnToChucThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToChucThiActionPerformed(evt);
            }
        });

        btnQTDangki.setBackground(new java.awt.Color(0, 0, 0));
        btnQTDangki.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQTDangki.setForeground(new java.awt.Color(255, 255, 255));
        btnQTDangki.setText("QT Đăng kí");
        btnQTDangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQTDangkiActionPerformed(evt);
            }
        });

        btnDangKiThi.setBackground(new java.awt.Color(0, 0, 0));
        btnDangKiThi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangKiThi.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKiThi.setText("Đăng kí thi");
        btnDangKiThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vtbChungChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNLGiangDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDT_HP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHocVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhieuThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXepLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTKB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPhanCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnToChucThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQTDangki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangKiThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDiemDanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnToChucThi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQTDangki, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDangKiThi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDiemDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnPhieuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnXepLop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(vtbChungChi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnNLGiangDay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDT_HP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void vtbChungChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtbChungChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vtbChungChiActionPerformed

    private void btnGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiangVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGiangVienActionPerformed

    private void btnNLGiangDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNLGiangDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNLGiangDayActionPerformed

    private void btnDT_HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDT_HPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDT_HPActionPerformed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void btnPhanCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPhanCongActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnPhieuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPhieuThuActionPerformed

    private void btnXepLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXepLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXepLopActionPerformed

    private void btnTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTKBActionPerformed

    private void btnDiemDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemDanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiemDanhActionPerformed

    private void btnToChucThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToChucThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToChucThiActionPerformed

    private void btnQTDangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQTDangkiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQTDangkiActionPerformed

    private void btnDangKiThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangKiThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDT_HP;
    private javax.swing.JButton btnDangKiThi;
    private javax.swing.JButton btnDiemDanh;
    private javax.swing.JButton btnGiangVien;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnNLGiangDay;
    private javax.swing.JButton btnPhanCong;
    private javax.swing.JButton btnPhieuThu;
    private javax.swing.JButton btnQTDangki;
    private javax.swing.JButton btnQuanLy;
    private javax.swing.JButton btnTKB;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnTaiKhoan11;
    private javax.swing.JButton btnTaiKhoan12;
    private javax.swing.JButton btnTaiKhoan13;
    private javax.swing.JButton btnTaiKhoan14;
    private javax.swing.JButton btnTaiKhoan15;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnToChucThi;
    private javax.swing.JButton btnXepLop;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton vtbChungChi;
    // End of variables declaration//GEN-END:variables
}
